import type { Metadata } from "next";
import { Rubik, Rubik_Mono_One } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import NavLink from "../_components/NavLink";
import DifficultySpan from "@/components/difficulty-span";
import { StoreHydration } from "@/components/store-hydration";
import { Toaster } from "sonner";

const rubikSans = Rubik({
  variable: "--font-rubik-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const rubikMono = Rubik_Mono_One({
  variable: "--font-rubik-mono",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubikSans.variable} ${rubikMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <StoreHydration />
        <NextIntlClientProvider>
          <header className="flex justify-center">
            <nav className="max-w-page w-full bg-gray-800">
              <ul className="flex gap-4 p-4">
                <li>
                  <NavLink href="/">Home</NavLink>
                </li>
                <li>
                  <NavLink href="/database">Database</NavLink>
                </li>
                <li>
                  <NavLink href="/tools">Tools</NavLink>
                </li>
                <li>
                  <NavLink href="/about">About</NavLink>
                </li>
                <li>
                  <NavLink href="/contact">Contact</NavLink>
                </li>
              </ul>
              <DifficultySpan />
            </nav>
          </header>

          <main>{children}</main>

          <footer className="mt-auto">Footer</footer>
        </NextIntlClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
