import { ProductName } from "../game/productNames";

export const WORKSTATION_PRESETS = {
  cheapClothing: [
    "classicCheapFemaleClothing",
    "classicCheapMaleClothing",
    "modernCheapFemaleClothing",
    "modernCheapMaleClothing",
  ],
  expensiveClothing: [
    "classicExpensiveFemaleClothing",
    "classicExpensiveMaleClothing",
    "modernExpensiveFemaleClothing",
    "modernExpensiveMaleClothing",
  ],
  electronics: [
    "rhythmByTreHeadphones",
    "noizeBossEarbuds",
    "artyFishSmartwatch",
    "zanaManSmartwatch",
    "artyFishPhone",
    "zanaManPhone",
  ],
  jewelry: ["cheapJewelry", "expensiveJewelry"],
  gifts: ["cheapGift", "expensiveGift"],
  books: [
    "novel",
    "pictureBook",
    "technicalManual",
    "youngNovel",
    "motivationalBook",
    "limitedEditionBook",
  ],
  bottledGoods: [
    "energyDrink",
    "sodaCan",
    "cupOfCoffee",
    "cupOfTea",
    "slushie",
    "whisky",
    "bottleOfWine",
    "beer",
    "margarita",
    "martini",
    "hairCareProduct",
  ],
  food: [
    "freshFood",
    "frozenFood",
    "croissant",
    "cupcake",
    "donut",
    "burger",
    "pizza",
    "kabob",
    "hotdog",
    "frenchFries",
    "salad",
    "iceCream",
    "cheesePlatter",
    "cottonCandy",
    "popcorn",
  ],
  gardenProducts: [
    "cheapFlower",
    "expensiveFlower",
    "apple",
    "banana",
    "pear",
    "tomato",
    "carrot",
    "lettuce",
  ],
} satisfies Record<string, ProductName[]>;
