export type IngredientName =
  | "Battery"
  | "Capacitors"
  | "Copper Clad Laminate"
  | "Fabric (Cheap)"
  | "Fabric (Expensive)"
  | "Glass"
  | "Integrated Circuits"
  | "Metal Band"
  | "Microphone"
  | "Plastic"
  | "Resistors"
  | "Speaker"
  | "Transistors"
  | "Uncut Gems (Cheap)"
  | "Uncut Gems (Expensive)"
  | "Cigar Paper"
  | "Cigarette Paper"
  | "Clay"
  | "Metal Wire"
  | "Paper Ream"
  | "Popcorn Kernels"
  | "Seeds (Apple)"
  | "Seeds (Banana)"
  | "Seeds (Carrot)"
  | "Seeds (Flower Cheap)"
  | "Seeds (Flower Expensive)"
  | "Seeds (Lettuce)"
  | "Seeds (Pear)"
  | "Seeds (Tomato)"
  | "Tobacco"
  | "Water"
  | "Barley"
  | "Blue Agave"
  | "Caffeine Extract"
  | "Carbon Dioxide"
  | "Cola Flavoring"
  | "Flavor Syrup"
  | "Grapes"
  | "Ground Coffee Beans"
  | "Hair Care Formula"
  | "Hops"
  | "Juniper Berries"
  | "Lime Juice"
  | "Sugar"
  | "Tea Leaves"
  | "Vermouth"
  | "Yeast"
  | "Bag of Lettuce"
  | "Bag of Tomatoes"
  | "Baking Mix"
  | "Butter"
  | "Cheese"
  | "Chicken Breast"
  | "Dough"
  | "Ground Beef"
  | "Milk"
  | "Onion"
  | "Pepper"
  | "Raw Sausage"
  | "Russet Potatoes"
  | "Vinaigrette";
