import { Importer } from "./importerNames";
import { IngredientName } from "./ingredientNames";

export type Ingredient = {
  amountPerBox: number;
  id: number;
  wholesalePrice: number;
  defaultMarketPrice: number;
  productSalesRatio: number;
  importers: Importer[];
};

export const ingredients: Record<IngredientName, Ingredient> = {
  battery: {
    amountPerBox: 500,
    id: 460,
    wholesalePrice: 16,
    defaultMarketPrice: 16,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  capacitors: {
    amountPerBox: 1000,
    id: 447,
    wholesalePrice: 6,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  copperCladLaminate: {
    amountPerBox: 500,
    id: 450,
    wholesalePrice: 8,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  fabricCheap: {
    amountPerBox: 150,
    id: 426,
    wholesalePrice: 6,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  fabricExpensive: {
    amountPerBox: 150,
    id: 427,
    wholesalePrice: 12,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  glass: {
    amountPerBox: 500,
    id: 453,
    wholesalePrice: 0.5,
    defaultMarketPrice: 0.5,
    productSalesRatio: 0.01,
    importers: ["maritimefreight", "globalharvest"],
  },
  integratedCircuits: {
    amountPerBox: 1000,
    id: 449,
    wholesalePrice: 10,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  metalBand: {
    amountPerBox: 150,
    id: 443,
    wholesalePrice: 0.6,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  microphone: {
    amountPerBox: 500,
    id: 456,
    wholesalePrice: 8,
    defaultMarketPrice: 8,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  plastic: {
    amountPerBox: 500,
    id: 461,
    wholesalePrice: 0.6,
    defaultMarketPrice: 0.6,
    productSalesRatio: 0.01,
    importers: ["maritimefreight", "globalharvest"],
  },
  resistors: {
    amountPerBox: 1000,
    id: 446,
    wholesalePrice: 4,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  speaker: {
    amountPerBox: 500,
    id: 457,
    wholesalePrice: 6,
    defaultMarketPrice: 6,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  transistors: {
    amountPerBox: 1000,
    id: 448,
    wholesalePrice: 8,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  uncutGemsCheap: {
    amountPerBox: 150,
    id: 435,
    wholesalePrice: 40,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  uncutGemsExpensive: {
    amountPerBox: 150,
    id: 436,
    wholesalePrice: 450,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["maritimefreight"],
  },
  cigarPaper: {
    amountPerBox: 1000,
    id: 432,
    wholesalePrice: 1,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  cigarettePaper: {
    amountPerBox: 1000,
    id: 433,
    wholesalePrice: 0.5,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  clay: {
    amountPerBox: 150,
    id: 493,
    wholesalePrice: 2.5,
    defaultMarketPrice: 2.5,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  metalWire: {
    amountPerBox: 500,
    id: 702,
    wholesalePrice: 3.5,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  paperReam: {
    amountPerBox: 300,
    id: 703,
    wholesalePrice: 6.25,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  popcornKernels: {
    amountPerBox: 500,
    id: 713,
    wholesalePrice: 0.01,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  appleSeed: {
    amountPerBox: 1000,
    id: 704,
    wholesalePrice: 0.5,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  bananaSeeds: {
    amountPerBox: 1000,
    id: 705,
    wholesalePrice: 0.5,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  carrotSeeds: {
    amountPerBox: 1000,
    id: 706,
    wholesalePrice: 0.5,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  flowerCheapSeeds: {
    amountPerBox: 1000,
    id: 707,
    wholesalePrice: 1.5,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  flowerExpensiveSeeds: {
    amountPerBox: 1000,
    id: 708,
    wholesalePrice: 3,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  lettuceSeeds: {
    amountPerBox: 1000,
    id: 711,
    wholesalePrice: 0.5,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  pearSeeds: {
    amountPerBox: 1000,
    id: 709,
    wholesalePrice: 0.5,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  tomatoSeeds: {
    amountPerBox: 1000,
    id: 710,
    wholesalePrice: 0.5,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  tobacco: {
    amountPerBox: 500,
    id: 431,
    wholesalePrice: 0.5,
    defaultMarketPrice: 0.5,
    productSalesRatio: 0.01,
    importers: ["globalharvest"],
  },
  water: {
    amountPerBox: 500,
    id: 471,
    wholesalePrice: 0.01,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["globalharvest", "aquaticbay"],
  },
  barley: {
    amountPerBox: 500,
    id: 475,
    wholesalePrice: 0.24,
    defaultMarketPrice: 0.24,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  blueAgave: {
    amountPerBox: 500,
    id: 489,
    wholesalePrice: 0.12,
    defaultMarketPrice: 0.12,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  caffeineExtract: {
    amountPerBox: 500,
    id: 699,
    wholesalePrice: 0.1,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  carbonDioxide: {
    amountPerBox: 500,
    id: 473,
    wholesalePrice: 0.01,
    defaultMarketPrice: 69,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  colaFlavoring: {
    amountPerBox: 500,
    id: 472,
    wholesalePrice: 0.02,
    defaultMarketPrice: 69,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  flavorSyrup: {
    amountPerBox: 500,
    id: 700,
    wholesalePrice: 0.04,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  grapes: {
    amountPerBox: 500,
    id: 478,
    wholesalePrice: 0.35,
    defaultMarketPrice: 0.35,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  groundCoffeeBeans: {
    amountPerBox: 500,
    id: 469,
    wholesalePrice: 0.12,
    defaultMarketPrice: 0.12,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  hairCareFormula: {
    amountPerBox: 500,
    id: 701,
    wholesalePrice: 2.5,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  hops: {
    amountPerBox: 500,
    id: 480,
    wholesalePrice: 0.02,
    defaultMarketPrice: 0.02,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  juniperBerries: {
    amountPerBox: 500,
    id: 483,
    wholesalePrice: 0.15,
    defaultMarketPrice: 0.15,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  limeJuice: {
    amountPerBox: 500,
    id: 491,
    wholesalePrice: 0.02,
    defaultMarketPrice: 69,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  sugar: {
    amountPerBox: 1500,
    id: 408,
    wholesalePrice: 0.05,
    defaultMarketPrice: 0.05,
    productSalesRatio: 0.01,
    importers: ["aquaticbay", "lunartide"],
  },
  teaLeaves: {
    amountPerBox: 500,
    id: 712,
    wholesalePrice: 0.12,
    defaultMarketPrice: 0.12,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  vermouth: {
    amountPerBox: 500,
    id: 485,
    wholesalePrice: 0.1,
    defaultMarketPrice: 69,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  yeast: {
    amountPerBox: 500,
    id: 476,
    wholesalePrice: 0.01,
    defaultMarketPrice: 0.01,
    productSalesRatio: 0.01,
    importers: ["aquaticbay"],
  },
  lettuce: {
    amountPerBox: 250,
    id: 181,
    wholesalePrice: 0.28,
    defaultMarketPrice: 2.12,
    productSalesRatio: 0.9,
    importers: ["lunartide"],
  },
  tomato: {
    amountPerBox: 500,
    id: 182,
    wholesalePrice: 0.29,
    defaultMarketPrice: 2.56,
    productSalesRatio: 0.9,
    importers: ["lunartide"],
  },
  bakingMix: {
    amountPerBox: 500,
    id: 395,
    wholesalePrice: 0.1,
    defaultMarketPrice: 0.1,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  butter: {
    amountPerBox: 500,
    id: 396,
    wholesalePrice: 0.5,
    defaultMarketPrice: 0.5,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  cheese: {
    amountPerBox: 500,
    id: 397,
    wholesalePrice: 0.32,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  chickenBreast: {
    amountPerBox: 500,
    id: 402,
    wholesalePrice: 0.35,
    defaultMarketPrice: 0.35,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  dough: {
    amountPerBox: 500,
    id: 400,
    wholesalePrice: 0.55,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  groundBeef: {
    amountPerBox: 500,
    id: 401,
    wholesalePrice: 0.55,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  milk: {
    amountPerBox: 500,
    id: 404,
    wholesalePrice: 0.05,
    defaultMarketPrice: 0.05,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  onion: {
    amountPerBox: 500,
    id: 405,
    wholesalePrice: 0.14,
    defaultMarketPrice: 0.14,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  pepper: {
    amountPerBox: 500,
    id: 406,
    wholesalePrice: 0.1,
    defaultMarketPrice: 0.1,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  rawSausage: {
    amountPerBox: 500,
    id: 410,
    wholesalePrice: 0.34,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  russetPotatoes: {
    amountPerBox: 500,
    id: 407,
    wholesalePrice: 0.4,
    defaultMarketPrice: 10,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
  vinaigrette: {
    amountPerBox: 500,
    id: 409,
    wholesalePrice: 0.1,
    defaultMarketPrice: 0.1,
    productSalesRatio: 0.01,
    importers: ["lunartide"],
  },
};
