import { IngredientName } from "./ingredientNames";
import { Importer } from "./importerNames";
import { ProductName } from "./productNames";
import { Price } from "./types";
import { WorkstationName } from "./machineNames";

export type Product = {
  purchasePrice: Price;
  boxAmount: number;
  importers: Importer[];
  ingredients: {
    [key in IngredientName]?: number;
  }[];
  productionRate: number;
  workstation: WorkstationName;
};

export const products: Record<ProductName, Product> = {
  "Gift (Cheap)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 200,
    importers: ["BlueStone Imports"],
    ingredients: [{ Clay: 50 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  "Gift (Expensive)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 200,
    importers: ["BlueStone Imports"],
    ingredients: [{ Glass: 100 }, { Plastic: 250 }, { Water: 100 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  Umbrella: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 200,
    importers: ["BlueStone Imports"],
    ingredients: [{ Plastic: 50 }, { "Metal Wire": 100 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  Cigar: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["United Ocean Import"],
    ingredients: [{ "Cigar Paper": 50 }, { Tobacco: 100 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  "Pack of Cigarettes": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["United Ocean Import"],
    ingredients: [{ "Cigarette Paper": 50 }, { Tobacco: 100 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  Novel: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 60,
    importers: ["BlueStone Imports"],
    ingredients: [{ "Paper Ream": 1 }, { "Fabric (Cheap)": 20 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  "Picture Book": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 90,
    importers: ["BlueStone Imports"],
    ingredients: [{ "Paper Ream": 1 }, { "Fabric (Cheap)": 20 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  "Technical Manual": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 60,
    importers: ["BlueStone Imports"],
    ingredients: [{ "Paper Ream": 5 }, { "Fabric (Expensive)": 50 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  "Youth Novel": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 90,
    importers: ["BlueStone Imports"],
    ingredients: [{ "Paper Ream": 1 }, { "Fabric (Cheap)": 20 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  "Motivational Book": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 60,
    importers: ["BlueStone Imports"],
    ingredients: [{ "Paper Ream": 3 }, { "Fabric (Expensive)": 50 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  "Limited Edition Book": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 60,
    importers: ["BlueStone Imports"],
    ingredients: [{ "Paper Ream": 2 }, { "Fabric (Expensive)": 100 }],
    productionRate: 100,
    workstation: "Consumer Goods Workstation",
  },
  "Paper Bag": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 1000,
    importers: [
      "JetCargo Imports",
      "SeaSide Internationals",
      "United Ocean Import",
      "BlueStone Imports",
    ],
    ingredients: [{ "Paper Ream": 2 }],
    productionRate: 500,
    workstation: "Consumer Goods Workstation",
  },
  "Flower (Cheap)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 40,
    importers: ["SeaSide Internationals"],
    ingredients: [{ "Seeds (Flower Cheap)": 100 }, { Water: 100 }],
    productionRate: 100,
    workstation: "Garden Workstation",
  },
  "Flower (Expensive)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 25,
    importers: ["SeaSide Internationals"],
    ingredients: [{ "Seeds (Flower Expensive)": 100 }, { Water: 100 }],
    productionRate: 100,
    workstation: "Garden Workstation",
  },
  "Bag of Pears": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["SeaSide Internationals"],
    ingredients: [{ "Seeds (Pear)": 50 }, { Water: 50 }],
    productionRate: 250,
    workstation: "Garden Workstation",
  },
  "Bag of Apples": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["SeaSide Internationals"],
    ingredients: [{ "Seeds (Apple)": 50 }, { Water: 50 }],
    productionRate: 250,
    workstation: "Garden Workstation",
  },
  "Bag of Tomatoes": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 500,
    importers: ["SeaSide Internationals", "Lunar Tide Shipments"],
    ingredients: [{ "Seeds (Tomato)": 50 }, { Water: 50 }],
    productionRate: 250,
    workstation: "Garden Workstation",
  },
  "Bag of Carrots": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["SeaSide Internationals"],
    ingredients: [{ "Seeds (Carrot)": 50 }, { Water: 50 }],
    productionRate: 250,
    workstation: "Garden Workstation",
  },
  "Bag of Lettuce": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 250,
    importers: ["SeaSide Internationals", "Lunar Tide Shipments"],
    ingredients: [{ "Seeds (Lettuce)": 50 }, { Water: 50 }],
    productionRate: 250,
    workstation: "Garden Workstation",
  },
  "Bag of Bananas": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["SeaSide Internationals"],
    ingredients: [{ "Seeds (Banana)": 50 }, { Water: 50 }],
    productionRate: 250,
    workstation: "Garden Workstation",
  },
  "Ice Cream": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["JetCargo Imports"],
    ingredients: [{ Milk: 200 }, { Sugar: 200 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  Cupcake: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["JetCargo Imports"],
    ingredients: [{ "Baking Mix": 200 }, { Milk: 100 }, { Sugar: 100 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  Popcorn: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 500,
    importers: ["SeaSide Internationals"],
    ingredients: [{ "Popcorn Kernels": 200 }, { Butter: 10 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  Donut: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["JetCargo Imports"],
    ingredients: [{ Dough: 200 }, { Milk: 100 }, { Sugar: 100 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  "Fresh Food": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["SeaSide Internationals"],
    ingredients: [
      { "Bag of Tomatoes": 100 },
      { "Ground Beef": 200 },
      { "Russet Potatoes": 200 },
    ],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  "Frozend Food": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["SeaSide Internationals"],
    ingredients: [{ "Chicken Breast": 200 }, { Vinaigrette: 100 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  Pizza: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 120,
    importers: ["JetCargo Imports"],
    ingredients: [{ Dough: 200 }, { Cheese: 200 }, { "Bag of Tomatoes": 100 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  "French Fries": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 400,
    importers: ["JetCargo Imports"],
    ingredients: [{ "Russet Potatoes": 200 }, { "Bag of Tomatoes": 50 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  "Chicken Kabob Skewer": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 200,
    importers: ["JetCargo Imports"],
    ingredients: [
      { "Chicken Breast": 200 },
      { Onion: 100 },
      { Pepper: 100 },
      { Vinaigrette: 100 },
    ],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  Burger: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["JetCargo Imports"],
    ingredients: [{ Cheese: 40 }, { Dough: 200 }, { "Ground Beef": 200 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  Croissant: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["JetCargo Imports"],
    ingredients: [{ Butter: 100 }, { Dough: 200 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  "Cheese Platter": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 500,
    importers: ["United Ocean Import"],
    ingredients: [{ Cheese: 200 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  Hotdog: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["JetCargo Imports"],
    ingredients: [
      { Dough: 200 },
      { "Raw Sausage": 200 },
      { "Bag of Tomatoes": 50 },
    ],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  "Cotton Candy": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 500,
    importers: ["SeaSide Internationals"],
    ingredients: [{ Sugar: 200 }],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  Salad: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 350,
    importers: ["JetCargo Imports"],
    ingredients: [
      { "Bag of Lettuce": 200 },
      { Onion: 100 },
      { Pepper: 100 },
      { "Bag of Tomatoes": 100 },
      { Vinaigrette: 100 },
    ],
    productionRate: 200,
    workstation: "Food Workstation",
  },
  "Energy Drink": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 500,
    importers: ["JetCargo Imports"],
    ingredients: [
      { "Caffeine Extract": 250 },
      { "Carbon Dioxide": 250 },
      { Sugar: 250 },
      { Water: 250 },
    ],
    productionRate: 250,
    workstation: "Bottled Goods Workstation",
  },
  "Cup of Tea": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 500,
    importers: ["JetCargo Imports"],
    ingredients: [{ "Tea Leaves": 250 }, { Water: 250 }],
    productionRate: 250,
    workstation: "Bottled Goods Workstation",
  },
  "Cup of Coffee": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 300,
    importers: ["JetCargo Imports"],
    ingredients: [{ "Ground Coffee Beans": 250 }, { Water: 250 }],
    productionRate: 250,
    workstation: "Bottled Goods Workstation",
  },
  Whisky: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["United Ocean Import"],
    ingredients: [{ Barley: 100 }, { Water: 50 }, { Yeast: 50 }],
    productionRate: 50,
    workstation: "Bottled Goods Workstation",
  },
  Slushie: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 500,
    importers: ["SeaSide Internationals"],
    ingredients: [{ "Flavor Syrup": 250 }, { Sugar: 250 }, { Water: 250 }],
    productionRate: 250,
    workstation: "Bottled Goods Workstation",
  },
  "Soda Can": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 120,
    importers: [
      "JetCargo Imports",
      "SeaSide Internationals",
      "United Ocean Import",
      "BlueStone Imports",
    ],
    ingredients: [
      { "Carbon Dioxide": 250 },
      { "Cola Flavoring": 250 },
      { Sugar: 250 },
      { Water: 250 },
    ],
    productionRate: 250,
    workstation: "Bottled Goods Workstation",
  },
  "Bottle of Wine": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 25,
    importers: ["United Ocean Import"],
    ingredients: [{ Grapes: 100 }, { Sugar: 50 }, { Yeast: 50 }],
    productionRate: 50,
    workstation: "Bottled Goods Workstation",
  },
  Margarita: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["United Ocean Import"],
    ingredients: [
      { Barley: 50 },
      { "Blue Agave": 100 },
      { "Lime Juice": 50 },
      { Water: 50 },
      { Yeast: 50 },
    ],
    productionRate: 50,
    workstation: "Bottled Goods Workstation",
  },
  Beer: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["United Ocean Import"],
    ingredients: [
      { Barley: 50 },
      { "Carbon Dioxide": 50 },
      { Hops: 50 },
      { Water: 50 },
      { Yeast: 50 },
    ],
    productionRate: 50,
    workstation: "Bottled Goods Workstation",
  },
  Martini: {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["United Ocean Import"],
    ingredients: [
      { Barley: 50 },
      { "Juniper Berries": 100 },
      { Vermouth: 50 },
      { Water: 50 },
      { Yeast: 50 },
    ],
    productionRate: 50,
    workstation: "Bottled Goods Workstation",
  },
  "Hair Care Product": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 40,
    importers: ["SeaSide Internationals"],
    ingredients: [{ "Hair Care Formula": 150 }, { Water: 150 }],
    productionRate: 150,
    workstation: "Bottled Goods Workstation",
  },
  "Jewelry (Cheap)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["BlueStone Imports"],
    ingredients: [{ "Uncut Gems (Cheap)": 60 }, { "Metal Band": 60 }],
    productionRate: 60,
    workstation: "Jewelry Workstation",
  },
  "Jewelry (Expensive)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: [],
    ingredients: [{ "Uncut Gems (Expensive)": 30 }, { "Metal Band": 30 }],
    productionRate: 30,
    workstation: "Jewelry Workstation",
  },
  "Rhythm By Tre Headphones": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 16,
    importers: ["BlueStone Imports"],
    ingredients: [
      { Capacitors: 120 },
      { "Copper Clad Laminate": 20 },
      { "Integrated Circuits": 60 },
      { Microphone: 60 },
      { Plastic: 20 },
      { Resistors: 120 },
      { Speaker: 120 },
      { Transistors: 120 },
    ],
    productionRate: 60,
    workstation: "Electronics Workstation",
  },
  "Noize Boss Earbuds": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 32,
    importers: ["BlueStone Imports"],
    ingredients: [
      { Capacitors: 60 },
      { "Copper Clad Laminate": 10 },
      { "Integrated Circuits": 60 },
      { Microphone: 60 },
      { Plastic: 10 },
      { Resistors: 60 },
      { Speaker: 120 },
      { Transistors: 60 },
    ],
    productionRate: 60,
    workstation: "Electronics Workstation",
  },
  "Arty Fish Phone": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 24,
    importers: [],
    ingredients: [
      { Battery: 30 },
      { Capacitors: 300 },
      { "Copper Clad Laminate": 30 },
      { Glass: 30 },
      { "Integrated Circuits": 60 },
      { Microphone: 30 },
      { Plastic: 30 },
      { Resistors: 300 },
      { Speaker: 30 },
      { Transistors: 300 },
    ],
    productionRate: 30,
    workstation: "Electronics Workstation",
  },
  "ZanaMan Phone": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 24,
    importers: [],
    ingredients: [
      { Battery: 30 },
      { Capacitors: 300 },
      { "Copper Clad Laminate": 30 },
      { Glass: 30 },
      { "Integrated Circuits": 60 },
      { Microphone: 30 },
      { Plastic: 30 },
      { Resistors: 300 },
      { Speaker: 30 },
      { Transistors: 300 },
    ],
    productionRate: 30,
    workstation: "Electronics Workstation",
  },
  "Arty Fish Smartwatch": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 32,
    importers: [],
    ingredients: [
      { Battery: 30 },
      { Capacitors: 60 },
      { "Copper Clad Laminate": 30 },
      { Glass: 5 },
      { "Integrated Circuits": 30 },
      { Microphone: 30 },
      { Plastic: 5 },
      { Resistors: 60 },
      { Speaker: 30 },
      { Transistors: 60 },
    ],
    productionRate: 30,
    workstation: "Electronics Workstation",
  },
  "ZanaMan Smartwatch": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 32,
    importers: [],
    ingredients: [
      { Battery: 30 },
      { Capacitors: 60 },
      { "Copper Clad Laminate": 30 },
      { Glass: 5 },
      { "Integrated Circuits": 30 },
      { Microphone: 30 },
      { Plastic: 5 },
      { Resistors: 60 },
      { Speaker: 30 },
      { Transistors: 60 },
    ],
    productionRate: 30,
    workstation: "Electronics Workstation",
  },
  "Clothing (Classic Cheap Male)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["United Ocean Import"],
    ingredients: [{ "Fabric (Cheap)": 120 }],
    productionRate: 60,
    workstation: "Clothing Workstation",
  },
  "Clothing (Classic Cheap Female)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["United Ocean Import"],
    ingredients: [{ "Fabric (Cheap)": 120 }],
    productionRate: 60,
    workstation: "Clothing Workstation",
  },
  "Clothing (Modern Cheap Male)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["United Ocean Import"],
    ingredients: [{ "Fabric (Cheap)": 120 }],
    productionRate: 60,
    workstation: "Clothing Workstation",
  },
  "Clothing (Modern Cheap Female)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: ["United Ocean Import"],
    ingredients: [{ "Fabric (Cheap)": 120 }],
    productionRate: 60,
    workstation: "Clothing Workstation",
  },
  "Clothing (Classic Expensive Male)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: [],
    ingredients: [{ "Fabric (Expensive)": 60 }],
    productionRate: 30,
    workstation: "Clothing Workstation",
  },
  "Clothing (Classic Expensive Female)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: [],
    ingredients: [{ "Fabric (Expensive)": 60 }],
    productionRate: 30,
    workstation: "Clothing Workstation",
  },
  "Clothing (Modern Expensive Male)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: [],
    ingredients: [{ "Fabric (Expensive)": 60 }],
    productionRate: 30,
    workstation: "Clothing Workstation",
  },
  "Clothing (Modern Expensive Female)": {
    purchasePrice: {
      easy: 0,
      normal: 0,
      hard: 0,
    },
    boxAmount: 50,
    importers: [],
    ingredients: [{ "Fabric (Expensive)": 60 }],
    productionRate: 30,
    workstation: "Clothing Workstation",
  },
};
